require('plugins')
require('options')
require('keymaps')
require('keybindings')
require('lualine-config')
require('treesitter-config')
require('nvim-tree-config')
require('autopairs-config')
require('telescope-config')
require('cmp-config')
require('harpoon-config')
require('lsp')
require('Comment').setup()
require('toogleterm-config')
require('neotest-config')
vim.cmd('colorscheme nordfox')

